# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IEEE @ UMich
email: ieee-officers@umich.edu
description: Copyright © 2018 IEEE UMich Student Branch. All Rights Reserved.
baseurl: '/ieee-website'    # the subpath of your site, e.g. /blog
url: 'https://ieee-umich.github.io' # the base hostname & protocol for your site
facebook_username: IEEEUMich
twitter_username: umichieee
github_username: ieee-umich

# Build settings
markdown: kramdown

# Making it compatible with MacOS
highlighter: rogue